name = "The Void"
author = "null2264"
version = "2025.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faf6eca2c2aad665194fe16f1cb631776a8efa2a7c2e9d249bcfdab06e1f631a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.162"
