name = "The Void"
author = "null2264"
version = "2025.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9bb97fa400b5e12de12cf12da7a5a683abf94db86f425c658ccf10fe01fda19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.162"
