name = "The Void"
author = "null2264"
version = "2025.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0229aeb04bbe50e4dcfa5ad8392b2a0c25b807a5a2c713065d8f1ce9743667f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.162"
