#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = [
  "id=back;operation=SET;size=1",
  "id=belt;operation=SET;size=1",
  "id=charm;operation=SET;size=2"
]
